/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectosemestral.Vistas.vendendor;

/**
 *
 * @author cetecom
 */
public class Nuevo_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_vendedor1
     */
    public Nuevo_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane_panel_principal = new javax.swing.JPanel();
        pane_fondo_Nuevo_Cliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pane_fondo_identifi = new javax.swing.JPanel();
        lbl_identificacion = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        pane_fondo_Nombre = new javax.swing.JPanel();
        lbl_Nombre = new javax.swing.JLabel();
        txt_identificacion = new javax.swing.JTextField();
        pane_fondo_email = new javax.swing.JPanel();
        lbl_e_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        pane_fondo_direccion = new javax.swing.JPanel();
        lbl_Direccion = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        pane_fondo_N = new javax.swing.JPanel();
        lbl_telefono = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        btn_volver = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        txt_fecha = new javax.swing.JTextField();
        pane_fondo_fecha = new javax.swing.JPanel();
        lbl_fecha_nac = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pane_panel_principal.setBackground(new java.awt.Color(207, 207, 207));

        pane_fondo_Nuevo_Cliente.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Cliente");

        javax.swing.GroupLayout pane_fondo_Nuevo_ClienteLayout = new javax.swing.GroupLayout(pane_fondo_Nuevo_Cliente);
        pane_fondo_Nuevo_Cliente.setLayout(pane_fondo_Nuevo_ClienteLayout);
        pane_fondo_Nuevo_ClienteLayout.setHorizontalGroup(
            pane_fondo_Nuevo_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_Nuevo_ClienteLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pane_fondo_Nuevo_ClienteLayout.setVerticalGroup(
            pane_fondo_Nuevo_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_Nuevo_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_fondo_identifi.setBackground(new java.awt.Color(153, 153, 153));

        lbl_identificacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_identificacion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_identificacion.setText("Idenificacion");

        javax.swing.GroupLayout pane_fondo_identifiLayout = new javax.swing.GroupLayout(pane_fondo_identifi);
        pane_fondo_identifi.setLayout(pane_fondo_identifiLayout);
        pane_fondo_identifiLayout.setHorizontalGroup(
            pane_fondo_identifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_identifiLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lbl_identificacion)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        pane_fondo_identifiLayout.setVerticalGroup(
            pane_fondo_identifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_identifiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_identificacion)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        txt_nombre.setForeground(new java.awt.Color(153, 153, 153));
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.setText("Nombre completo");

        pane_fondo_Nombre.setBackground(new java.awt.Color(176, 176, 176));

        lbl_Nombre.setBackground(new java.awt.Color(238, 238, 238));
        lbl_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre.setText("Nombre");

        javax.swing.GroupLayout pane_fondo_NombreLayout = new javax.swing.GroupLayout(pane_fondo_Nombre);
        pane_fondo_Nombre.setLayout(pane_fondo_NombreLayout);
        pane_fondo_NombreLayout.setHorizontalGroup(
            pane_fondo_NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_NombreLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_Nombre)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        pane_fondo_NombreLayout.setVerticalGroup(
            pane_fondo_NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_NombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Nombre)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        txt_identificacion.setForeground(new java.awt.Color(153, 153, 153));
        txt_identificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_identificacion.setText("RUT/PASAPORTE");

        pane_fondo_email.setBackground(new java.awt.Color(176, 176, 176));

        lbl_e_email.setBackground(new java.awt.Color(238, 238, 238));
        lbl_e_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_e_email.setText("E-EMAIL");

        javax.swing.GroupLayout pane_fondo_emailLayout = new javax.swing.GroupLayout(pane_fondo_email);
        pane_fondo_email.setLayout(pane_fondo_emailLayout);
        pane_fondo_emailLayout.setHorizontalGroup(
            pane_fondo_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_emailLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_e_email)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        pane_fondo_emailLayout.setVerticalGroup(
            pane_fondo_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_emailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_e_email)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        txt_email.setForeground(new java.awt.Color(153, 153, 153));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_email.setText("EXAMPLE@DUOCUC.CL");

        pane_fondo_direccion.setBackground(new java.awt.Color(176, 176, 176));

        lbl_Direccion.setBackground(new java.awt.Color(238, 238, 238));
        lbl_Direccion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Direccion.setText("DIRECCION");

        javax.swing.GroupLayout pane_fondo_direccionLayout = new javax.swing.GroupLayout(pane_fondo_direccion);
        pane_fondo_direccion.setLayout(pane_fondo_direccionLayout);
        pane_fondo_direccionLayout.setHorizontalGroup(
            pane_fondo_direccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_direccionLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_Direccion)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pane_fondo_direccionLayout.setVerticalGroup(
            pane_fondo_direccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_direccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Direccion)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        txt_direccion.setForeground(new java.awt.Color(153, 153, 153));
        txt_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_direccion.setText("DIRECCION");
        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });

        pane_fondo_N.setBackground(new java.awt.Color(176, 176, 176));

        lbl_telefono.setBackground(new java.awt.Color(238, 238, 238));
        lbl_telefono.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefono.setText("N°TELEFONO");

        javax.swing.GroupLayout pane_fondo_NLayout = new javax.swing.GroupLayout(pane_fondo_N);
        pane_fondo_N.setLayout(pane_fondo_NLayout);
        pane_fondo_NLayout.setHorizontalGroup(
            pane_fondo_NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_NLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_telefono)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pane_fondo_NLayout.setVerticalGroup(
            pane_fondo_NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_NLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_telefono)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        txt_telefono.setForeground(new java.awt.Color(153, 153, 153));
        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_telefono.setText("+56  9 5555 5555");
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });

        btn_volver.setBackground(new java.awt.Color(102, 102, 102));
        btn_volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_volver.setText("VOLVER");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        btn_aceptar.setBackground(new java.awt.Color(102, 102, 102));
        btn_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        txt_fecha.setForeground(new java.awt.Color(153, 153, 153));
        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha.setText("MM/DD/YYYY");
        txt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaActionPerformed(evt);
            }
        });

        pane_fondo_fecha.setBackground(new java.awt.Color(176, 176, 176));

        lbl_fecha_nac.setBackground(new java.awt.Color(238, 238, 238));
        lbl_fecha_nac.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fecha_nac.setText("Fecha Naciminento");

        javax.swing.GroupLayout pane_fondo_fechaLayout = new javax.swing.GroupLayout(pane_fondo_fecha);
        pane_fondo_fecha.setLayout(pane_fondo_fechaLayout);
        pane_fondo_fechaLayout.setHorizontalGroup(
            pane_fondo_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_fechaLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lbl_fecha_nac)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pane_fondo_fechaLayout.setVerticalGroup(
            pane_fondo_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_fechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_fecha_nac)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pane_panel_principalLayout = new javax.swing.GroupLayout(pane_panel_principal);
        pane_panel_principal.setLayout(pane_panel_principalLayout);
        pane_panel_principalLayout.setHorizontalGroup(
            pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_panel_principalLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_panel_principalLayout.createSequentialGroup()
                        .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_panel_principalLayout.createSequentialGroup()
                        .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pane_panel_principalLayout.createSequentialGroup()
                                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pane_fondo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pane_fondo_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pane_fondo_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pane_panel_principalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_direccion)
                                            .addComponent(txt_telefono)))
                                    .addGroup(pane_panel_principalLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pane_panel_principalLayout.createSequentialGroup()
                                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pane_fondo_identifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_panel_principalLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(pane_fondo_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_identificacion)
                                    .addComponent(txt_nombre)))
                            .addGroup(pane_panel_principalLayout.createSequentialGroup()
                                .addComponent(pane_fondo_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_fecha))
                            .addComponent(pane_fondo_Nuevo_Cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82))))
        );
        pane_panel_principalLayout.setVerticalGroup(
            pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_panel_principalLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(pane_fondo_Nuevo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane_fondo_identifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_identificacion))
                .addGap(24, 24, 24)
                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pane_fondo_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pane_fondo_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_email)
                    .addComponent(pane_fondo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane_fondo_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pane_fondo_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pane_panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(pane_panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pane_panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void txt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Direccion;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_e_email;
    private javax.swing.JLabel lbl_fecha_nac;
    private javax.swing.JLabel lbl_identificacion;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JPanel pane_fondo_N;
    private javax.swing.JPanel pane_fondo_Nombre;
    private javax.swing.JPanel pane_fondo_Nuevo_Cliente;
    private javax.swing.JPanel pane_fondo_direccion;
    private javax.swing.JPanel pane_fondo_email;
    private javax.swing.JPanel pane_fondo_fecha;
    private javax.swing.JPanel pane_fondo_identifi;
    private javax.swing.JPanel pane_panel_principal;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_identificacion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
